# Generated by Django 5.1.2 on 2024-11-29 07:03

from django.db import migrations


def create_super_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    # 定义默认角色
    superuser_details = {
        'username': 'root',
        'password': 'root',
        'email': 'root@root.com',
    }
    # 检查是否已经存在同名用户
    if not User.objects.filter(username='root').exists():
        # 创建超级用户
        user = User.objects.create_superuser(username='root', password='root', email='root@root.com')
        role = apps.get_model('models', 'Role')
        role_obj = role.objects.get(name='管理员')
        user_info = apps.get_model('models', 'UserInfo')
        user_info.objects.create(
            user=user,
            role=role_obj,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_insert_default_roles'),
    ]

    operations = [
        migrations.RunPython(create_super_user),
    ]
