# Generated by Django 5.1.2 on 2024-12-03 06:49

from django.db import migrations
from models.models import *


def create_default_category(apps, schema_editor):
    Category = apps.get_model('models', 'Category')
    SubCategory = apps.get_model('models', 'SubCategory')
    sub_category_name = {
        '新鲜果蔬': ['根茎类', '叶茎类', '瓜果类', '浆果类', '柑橘类'],
        '有机谷物': ['大米类', '小麦及面粉类', '杂粮类', '燕麦及麦片'],
        '有机肉类': ['牛肉', '猪肉', '鸡肉']
    }
    for category_name, sub_category_list in sub_category_name.items():
        category_object, created = Category.objects.get_or_create(name=category_name)
        for sub_category_name in sub_category_list:
            SubCategory.objects.create(category=category_object, name=sub_category_name)


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_create_superuser'),
    ]

    operations = [
        migrations.RunPython(create_default_category),
    ]
