# Generated by Django 5.1.2 on 2024-12-12 06:57

from django.db import migrations


def create_test_user(apps, schema_editor):
    user_class = apps.get_model('auth', 'User')
    user_info_class = apps.get_model('models', 'UserInfo')
    role_class = apps.get_model('models', 'Role')
    role_seller = role_class.objects.get(name='商家')
    # 插入商家数据
    seller_user_list = ['商家-1', '商家-2']
    for username in seller_user_list:
        user = user_class.objects.create_user(
            username=username,
            password='123',
            email='test@163.com'
        )
        user_info_class.objects.create(
            user=user,
            role=role_seller,
            name=username
        )
    # 插入用户数据
    user_list = ['用户-1', '用户-2', '用户-3']
    role_user = role_class.objects.get(name='用户')
    for username in user_list:
        user = user_class.objects.create_user(
            username=username,
            password='123',
            email='test@163.com'
        )
        user_info_class.objects.create(
            user=user,
            role=role_user,
            name=username
        )

class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_create_default_category'),
    ]

    operations = [
        migrations.RunPython(create_test_user),
    ]
